# Generated by Django 2.2.12 on 2020-04-20 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'verbose_name_plural': 'SkillCategories'},
        ),
    ]
