# Generated by Django 2.2.11 on 2020-04-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personskill',
            name='with_user',
        ),
    ]
