# Generated by Django 2.2.11 on 2020-04-26 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_personskill_with_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('L', 'learn'), ('T', 'teach'), ('P', 'partner')], default='L', max_length=2)),
                ('rating', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='skills',
        ),
        migrations.DeleteModel(
            name='PersonSkill',
        ),
        migrations.AddField(
            model_name='relationship',
            name='from_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from+', to='user.Person'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Skill'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='to_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to+', to='user.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='relationships',
            field=models.ManyToManyField(blank=True, related_name='related_to', through='user.Relationship', to='user.Person'),
        ),
    ]
