# Generated by Django 2.2.11 on 2020-04-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200426_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='skills',
            field=models.ManyToManyField(blank=True, to='user.Skill'),
        ),
    ]
